import type { TFunction } from 'i18next';
import type { PilotReportStaticCopy } from './types';

export function buildPilotReportStaticCopy(t: TFunction): PilotReportStaticCopy {
  return {
    documentTitle: t('pilotReport.documentTitle'),
    coverEyebrow: t('pilotReport.coverEyebrow'),
    coverTitle: t('pilotReport.coverTitle'),
    coverSubtitle: t('pilotReport.coverSubtitle'),
    internalBadge: t('pilotReport.internalBadge'),
    labelCourse: t('pilotReport.labelCourse'),
    labelSubject: t('pilotReport.labelSubject'),
    labelGenerated: t('pilotReport.labelGenerated'),
    labelScope: t('pilotReport.labelScope'),
    labelAssignmentsInScope: t('pilotReport.labelAssignmentsInScope'),
    labelCohortSize: t('pilotReport.labelCohortSize'),
    labelPilotDates: t('pilotReport.labelPilotDates'),
    reportIdLabel: t('pilotReport.reportIdLabel'),
    sectionExecutiveSummary: t('pilotReport.sectionExecutiveSummary'),
    cohortParticipants: t('pilotReport.cohortParticipants'),
    cohortReady: t('pilotReport.cohortReady'),
    cohortCoach: t('pilotReport.cohortCoach'),
    cohortRedirect: t('pilotReport.cohortRedirect'),
    cohortNotReady: t('pilotReport.cohortNotReady'),
    cohortNotAssessed: t('pilotReport.cohortNotAssessed'),
    cohortRoleFitDistribution: t('pilotReport.cohortRoleFitDistribution'),
    scopeFactsLine: t('pilotReport.scopeFactsLine'),
    recommendationTitle: t('pilotReport.recommendationTitle'),
    findingsTitle: t('pilotReport.findingsTitle'),
    findingStrongest: t('pilotReport.findingStrongest'),
    findingGap: t('pilotReport.findingGap'),
    findingNextAction: t('pilotReport.findingNextAction'),
    recommendationFallback: t('pilotReport.recommendationFallback'),
    sectionCapabilitySnapshot: t('pilotReport.sectionCapabilitySnapshot'),
    sectionCapabilitySnapshotDesc: t('pilotReport.sectionCapabilitySnapshotDesc'),
    sectionDecisionTable: t('pilotReport.sectionDecisionTable'),
    sectionDecisionTableDesc: t('pilotReport.sectionDecisionTableDesc'),
    colParticipant: t('pilotReport.colParticipant'),
    colReadiness: t('pilotReport.colReadiness'),
    colFit: t('pilotReport.colFit'),
    colStrength: t('pilotReport.colStrength'),
    colRisk: t('pilotReport.colRisk'),
    colNextAction: t('pilotReport.colNextAction'),
    colConfidence: t('pilotReport.colConfidence'),
    readinessLabels: {
      ready: t('pilotReport.readinessReady'),
      coach: t('pilotReport.readinessCoach'),
      redirect: t('pilotReport.readinessRedirect'),
      not_ready: t('pilotReport.readinessNotReady'),
    },
    roleFitLabels: {
      builder: t('pilotReport.roleBuilder'),
      analyst: t('pilotReport.roleAnalyst'),
      champion: t('pilotReport.roleChampion'),
      enablement: t('pilotReport.roleEnablement'),
      training: t('pilotReport.roleTraining'),
    },
    confidenceLabels: {
      high: t('pilotReport.confidenceHigh'),
      medium: t('pilotReport.confidenceMedium'),
      low: t('pilotReport.confidenceLow'),
    },
    dimensionLabels: {
      builderExecution: t('pilotReport.dimBuilderExecution'),
      conceptualFluency: t('pilotReport.dimConceptualFluency'),
      platformFit: t('pilotReport.dimPlatformFit'),
      debuggingIndependence: t('pilotReport.dimDebuggingIndependence'),
      communication: t('pilotReport.dimCommunication'),
    },
    notAssessed: t('pilotReport.notAssessed'),
    sectionAppendix: t('pilotReport.sectionAppendix'),
    sectionAppendixDesc: t('pilotReport.sectionAppendixDesc'),
    appendixCompleted: t('pilotReport.appendixCompleted'),
    appendixRisk: t('pilotReport.appendixRisk'),
    appendixNextAction: t('pilotReport.appendixNextAction'),
    appendixObservedSignals: t('pilotReport.appendixObservedSignals'),
    appendixWhyBullets: t('pilotReport.appendixWhyBullets'),
    sectionMethodology: t('pilotReport.sectionMethodology'),
    legendReadinessTitle: t('pilotReport.legendReadinessTitle'),
    legendReadinessReady: t('pilotReport.legendReadinessReady'),
    legendReadinessCoach: t('pilotReport.legendReadinessCoach'),
    legendReadinessRedirect: t('pilotReport.legendReadinessRedirect'),
    legendReadinessNotReady: t('pilotReport.legendReadinessNotReady'),
    legendWeighting: t('pilotReport.legendWeighting'),
    legendConfidence: t('pilotReport.legendConfidence'),
    footerDisclaimer: t('pilotReport.footerDisclaimer'),
    noData: t('pilotReport.noData'),
  };
}
