import type {
  PilotParticipantRow,
  PilotReportData,
  PilotReportStaticCopy,
} from './types';

export const testStaticCopy: PilotReportStaticCopy = {
  documentTitle: 'Pilot Report',
  coverEyebrow: 'Perleap Pilot Report',
  coverTitle: 'Builder Readiness & Role Fit',
  coverSubtitle: 'Management decision report.',
  internalBadge: 'Internal — management use',
  labelCourse: 'Course',
  labelSubject: 'Subject',
  labelGenerated: 'Generated',
  labelScope: 'Scope',
  labelAssignmentsInScope: 'Assignments in scope',
  labelCohortSize: 'Cohort size',
  labelPilotDates: 'Pilot dates',
  reportIdLabel: 'Report ID',
  sectionExecutiveSummary: 'Executive Summary',
  cohortParticipants: 'Participants assessed',
  cohortReady: 'Ready for supervised real work',
  cohortCoach: 'Almost ready — needs targeted practice before real work',
  cohortRedirect: 'Better fit in another role',
  cohortNotReady: 'Not ready to continue as builder',
  cohortNotAssessed: 'Not assessed',
  cohortRoleFitDistribution: 'Recommended role-fit distribution',
  scopeFactsLine: 'Pilot scope',
  recommendationTitle: 'Recommendation',
  findingsTitle: 'Key findings',
  findingStrongest: 'Strongest capability',
  findingGap: 'Main gap',
  findingNextAction: 'Top next action',
  recommendationFallback:
    '{{ready}} ready, {{coachOrTraining}} need coaching/training, {{redirect}} redirect.',
  sectionCapabilitySnapshot: 'Cohort Capability Snapshot',
  sectionCapabilitySnapshotDesc: 'Mean scores (0–100).',
  sectionDecisionTable: 'Participant Decision Table',
  sectionDecisionTableDesc: 'AI-generated decisions.',
  colParticipant: 'Participant',
  colReadiness: 'Readiness',
  colFit: 'Recommended fit',
  colStrength: 'Key strength',
  colRisk: 'Main risk',
  colNextAction: 'Next action',
  colConfidence: 'Confidence',
  readinessLabels: {
    ready: 'Ready',
    coach: 'Almost ready',
    redirect: 'Redirect',
    not_ready: 'Not ready',
  },
  roleFitLabels: {
    builder: 'Builder / implementer',
    analyst: 'Solution analyst',
    champion: 'Platform champion',
    enablement: 'Customer enablement',
    training: 'Further training',
  },
  confidenceLabels: {
    high: 'High',
    medium: 'Medium',
    low: 'Low',
  },
  dimensionLabels: {
    builderExecution: 'Builder execution',
    conceptualFluency: 'Conceptual fluency',
    platformFit: 'Platform fit',
    debuggingIndependence: 'Debugging independence',
    communication: 'Communication',
  },
  notAssessed: 'Not assessed — insufficient data or generation failed',
  sectionAppendix: 'Appendix — Participant Summaries',
  sectionAppendixDesc: 'Short evidence-based summary per participant.',
  appendixCompleted: 'Completed',
  appendixRisk: 'Risk',
  appendixNextAction: 'Next action',
  appendixObservedSignals: 'Observed builder signals',
  appendixWhyBullets: 'Why this decision',
  sectionMethodology: 'How to read this report',
  legendReadinessTitle: 'Readiness labels',
  legendReadinessReady: 'Ready — can move into supervised real implementation work now.',
  legendReadinessCoach: 'Almost ready — has potential but needs targeted practice before real work.',
  legendReadinessRedirect: 'Redirect — not ideal as a hands-on builder; may fit another role.',
  legendReadinessNotReady: 'Not ready — should not continue into platform implementation yet.',
  legendWeighting:
    'Readiness judgments weight builder execution 30%, platform fit 25%, debugging independence 20%, conceptual fluency 15%, and communication 10%.',
  legendConfidence:
    'Confidence reflects evidence quality: high with rich evidence across assignments; low when evidence is thin.',
  footerDisclaimer:
    'Signals are derived from observed learning evidence during the pilot, not a final diagnosis.',
  noData: '—',
};

export const assessedParticipant: PilotParticipantRow = {
  id: 'student-1',
  name: 'Dana Cohen',
  completedInScope: 5,
  assignmentsInScope: 6,
  assessed: true,
  dimensions: {
    builderExecution: 80,
    conceptualFluency: 70,
    platformFit: 75,
    debuggingIndependence: 60,
    communication: 85,
  },
  weightedScore: 74,
  placementPriority: 9,
  readiness: 'ready',
  roleFit: 'builder',
  keyStrength: 'Ships working builds quickly.',
  mainRisk: 'Gets stuck on multi-step debugging.',
  nextAction: 'Assign to supervised client build.',
  confidence: 'high',
  whyBullets: [
    'Completed 5 of 6 scoped assignments with working builds.',
    'Strong communication in assignment feedback excerpts.',
  ],
};

export const failedParticipant: PilotParticipantRow = {
  id: 'student-2',
  name: 'Noa Levi',
  completedInScope: 1,
  assignmentsInScope: 6,
  assessed: false,
  dimensions: null,
  weightedScore: null,
  placementPriority: null,
  readiness: null,
  roleFit: null,
  keyStrength: '',
  mainRisk: '',
  nextAction: '',
  confidence: null,
  whyBullets: [],
};

export const basePilotReport: PilotReportData = {
  meta: {
    classroomLabel: 'INSAIT Builders Pilot',
    subject: 'AI Solutions',
    filterSummary: 'All sections | All assignments',
    generatedAtDisplay: 'Jun 11, 2026',
    language: 'en',
    dir: 'ltr',
    reportId: 'PR-insait-builders-pilot-20260611-A1B2',
    logoDataUri: 'data:image/svg+xml;base64,PHN2Zy8+',
    assignmentsInScope: 6,
    cohortSize: 2,
    pilotDateRange: 'Jan 1, 2026 – Mar 31, 2026',
  },
  cohort: {
    participantsAssessed: 1,
    participantsTotal: 2,
    readinessCounts: { ready: 1, coach: 0, redirect: 0, not_ready: 0 },
    roleFitCounts: { builder: 1, analyst: 0, champion: 0, enablement: 0, training: 0 },
    meanDimensions: {
      builderExecution: 80,
      conceptualFluency: 70,
      platformFit: 75,
      debuggingIndependence: 60,
      communication: 85,
    },
  },
  summary: {
    recommendation: 'Move 1 participant into a supervised builder track now.',
    strongestCapability: 'Builder execution is the strongest cohort capability.',
    mainGap: 'Debugging independence is the main gap.',
    topNextAction: 'Run a focused debugging workshop.',
  },
  participants: [assessedParticipant, failedParticipant],
  staticCopy: testStaticCopy,
};
